import cat from "./assets/cat2.jpg";

const data = [
  {
    id: 1,
    name: "Coke",
    src: cat,
    description: "Sweet coke",
    phone: "890-193-2932",
    email: "adoptcoke@gmail.com",
    tags: ["Affectionate", "Playful", "Chubby"],
  },
  {
    id: 2,
    name: "Sunni",
    src: cat,
    description: "Sunni is very sunny",
    phone: "890-343-4523",
    email: "sscandy@yahoo.com",
    tags: ["Moody", "Stubborn"],
  },
  {
    id: 3,
    name: "Dobby",
    src: cat,
    description: "Dobby is very sunny",
    phone: "890-343-4523",
    email: "sscandy@yahoo.com",
    tags: ["Moody", "Stubborn"],
  },
  {
    id: 4,
    name: "Monmon",
    src: cat,
    description: "Monmon is very sunny",
    phone: "890-343-4523",
    email: "sscandy@yahoo.com",
    tags: ["Moody", "Stubborn"],
  },
  {
    id: 5,
    name: "Tobi",
    src: cat,
    description: "Tobi like Tobi from Naruto",
    phone: "890-343-4523",
    email: "sscandy@yahoo.com",
    tags: ["Moody", "Stubborn, Fiesty"],
  },
  {
    id: 6,
    name: "Sunni",
    src: cat,
    description: "Sunni is very sunny",
    phone: "890-343-4523",
    email: "sscandy@yahoo.com",
    tags: ["Moody", "Stubborn"],
  },
  {
    id: 7,
    name: "Chata",
    src: cat,
    description: "Sunni is very sunny",
    phone: "890-343-4573",
    email: "sscandy@yahoo.com",
    tags: ["Moody", "Stubborn"],
  },
  {
    id: 8,
    name: "Mikasa",
    src: cat,
    description: "Aot Mikasa",
    phone: "890-343-4523",
    email: "sscandy@yahoo.com",
    tags: ["Moody", "Stubborn"],
  },
  {
    id: 9,
    name: "Cocoa",
    src: cat,
    description: "Cocoa is very sunny",
    phone: "890-343-4523",
    email: "sscandy@yahoo.com",
    tags: ["Moody", "Stubborn"],
  },
  {
    id: 10,
    name: "Sunni",
    src: cat,
    description: "Sunni is very sunny",
    phone: "890-343-4523",
    email: "sscandy@yahoo.com",
    tags: ["Moody", "Stubborn"],
  },
  {
    id: 11,
    name: "Simp",
    src: cat,
    description: "Sunni is very sunny",
    phone: "890-343-4523",
    email: "sscandy@yahoo.com",
    tags: ["Moody", "Stubborn"],
  },
  {
    id: 12,
    name: "Sunni",
    src: cat,
    description: "Sunni is very sunny",
    phone: "890-343-4523",
    email: "sscandy@yahoo.com",
    tags: ["Moody", "Stubborn"],
  },
  {
    id: 13,
    name: "Sunni",
    src: cat,
    description: "Sunni is very sunny",
    phone: "890-343-4523",
    email: "sscandy@yahoo.com",
    tags: ["Moody", "Stubborn"],
  },
  {
    id: 14,
    name: "Joji",
    src: cat,
    description: "Joji is very sunny",
    phone: "890-343-4523",
    email: "sscandy@yahoo.com",
    tags: ["Moody", "Stubborn"],
  },
  {
    id: 15,
    name: "Sunni",
    src: cat,
    description: "Sunni is very sunny",
    phone: "890-343-4523",
    email: "sscandy@yahoo.com",
    tags: ["Moody", "Stubborn"],
  },
  {
    id: 16,
    name: "Eren",
    src: cat,
    description: "Eren is very sunny",
    phone: "890-343-4523",
    email: "sscandy@yahoo.com",
    tags: ["Moody", "Stubborn"],
  },
];

export default data;
